import json
from backend.database.database import SessionLocal, engine, Base
from backend.database.models import (
    HazardZoneModel,
    SensorNodeModel,
    CrowdsourceReportModel,
    TacticalUnitModel,
    ReliefShelterModel,
    AuditLogModel,
)

INITIAL_HAZARD_ZONES = [
    {
        "id": "zone-sk-01",
        "name": "Teesta Basin (NH-10 Corridor)",
        "subDivision": "Mangan Sub-Division",
        "corridor": "Km 34.2 to 41.8",
        "state": "sikkim",
        "slopeGradient": "48.6°",
        "soilPoreSaturation": "92.4%",
        "displacementRate": "14.2 mm/hr",
        "pwpPressure": "284 kPa",
        "riskStatus": "CRITICAL RED",
        "rfConfidence": "98.4%",
        "lstmEvac": "03h 45m",
        "highwaySegment": "NH-10 (Km 34.2 – 41.8)",
        "bridgesExposed": "Teesta-V Bailey Br. (2.4 km downstream)",
        "populationRunout": "1,420 Residents (Lower Singtam)",
        "coords": "27.5312° N, 88.5134° E",
        "elevation": "1,480 m",
        "top": "36%",
        "left": "38%",
        "isCritical": True,
        "hazardScore": 9.2,
    },
    {
        "id": "zone-as-02",
        "name": "Dima Hasao Hill Tracts",
        "subDivision": "Haflong Sector",
        "corridor": "Lumding–Badarpur Railway Line",
        "state": "assam",
        "slopeGradient": "39.2°",
        "soilPoreSaturation": "78.1%",
        "displacementRate": "6.4 mm/hr",
        "pwpPressure": "196 kPa",
        "riskStatus": "ADVISORY ORANGE",
        "rfConfidence": "86.2%",
        "lstmEvac": "08h 15m",
        "highwaySegment": "NH-27 Mahur Bypass",
        "bridgesExposed": "Jatinga Viaduct #4",
        "populationRunout": "680 Residents",
        "coords": "25.1764° N, 93.0248° E",
        "elevation": "960 m",
        "top": "52%",
        "left": "62%",
        "isCritical": False,
        "hazardScore": 6.8,
    },
    {
        "id": "zone-ml-03",
        "name": "Sohra Rim Pass (Cherrapunji)",
        "subDivision": "East Khasi Hills",
        "corridor": "Shella–Sohra Highway",
        "state": "meghalaya",
        "slopeGradient": "54.1°",
        "soilPoreSaturation": "86.9%",
        "displacementRate": "9.8 mm/hr",
        "pwpPressure": "240 kPa",
        "riskStatus": "CRITICAL RED",
        "rfConfidence": "94.1%",
        "lstmEvac": "04h 50m",
        "highwaySegment": "SH-5 Sohra Link",
        "bridgesExposed": "Wahkaba Gorge Span",
        "populationRunout": "940 Residents",
        "coords": "25.2986° N, 91.7322° E",
        "elevation": "1,310 m",
        "top": "58%",
        "left": "44%",
        "isCritical": True,
        "hazardScore": 8.7,
    },
    {
        "id": "zone-mn-04",
        "name": "Tupul Railway Yard Sub-Catchment",
        "subDivision": "Noney District",
        "corridor": "Jiribam–Imphal Rail Alignment",
        "state": "manipur",
        "slopeGradient": "44.5°",
        "soilPoreSaturation": "88.2%",
        "displacementRate": "11.6 mm/hr",
        "pwpPressure": "262 kPa",
        "riskStatus": "CRITICAL RED",
        "rfConfidence": "96.7%",
        "lstmEvac": "04h 10m",
        "highwaySegment": "NH-37 Imphal–Silchar",
        "bridgesExposed": "Ijei River Pier #2",
        "populationRunout": "1,120 Residents & Camp",
        "coords": "24.8167° N, 93.6833° E",
        "elevation": "680 m",
        "top": "68%",
        "left": "74%",
        "isCritical": True,
        "hazardScore": 9.0,
    },
    {
        "id": "zone-ar-05",
        "name": "Bhalukpong–Bomdila Ghat Road",
        "subDivision": "West Kameng",
        "corridor": "Balipara–Charduar–Tawang Road",
        "state": "arunachal",
        "slopeGradient": "42.0°",
        "soilPoreSaturation": "62.4%",
        "displacementRate": "2.8 mm/hr",
        "pwpPressure": "135 kPa",
        "riskStatus": "NOMINAL GREEN",
        "rfConfidence": "91.0%",
        "lstmEvac": "24h+ Stable",
        "highwaySegment": "NH-13 Trans-Arunachal Hwy",
        "bridgesExposed": "Kameng River Suspension",
        "populationRunout": "320 Residents",
        "coords": "27.0125° N, 92.6458° E",
        "elevation": "1,890 m",
        "top": "24%",
        "left": "52%",
        "isCritical": False,
        "hazardScore": 2.8,
    },
    {
        "id": "zone-uk-06",
        "name": "Uttarkashi Ridge Bypass",
        "subDivision": "Bhatwari Sub-Division",
        "corridor": "Gangotri Highway NH-34 (Km 42.0 to 49.5)",
        "state": "uttarakhand",
        "slopeGradient": "41.8°",
        "soilPoreSaturation": "81.6%",
        "displacementRate": "7.6 mm/hr",
        "pwpPressure": "218 kPa",
        "riskStatus": "ADVISORY ORANGE",
        "rfConfidence": "89.7%",
        "lstmEvac": "06h 20m",
        "highwaySegment": "NH-34 Gangotri Artery",
        "bridgesExposed": "Maneri River Crossing",
        "populationRunout": "720 Residents",
        "coords": "30.7268° N, 78.4354° E",
        "elevation": "1,158 m",
        "top": "18%",
        "left": "18%",
        "isCritical": False,
        "hazardScore": 6.4,
    },
    {
        "id": "zone-na-07",
        "name": "Kohima Escarpment",
        "subDivision": "Kohima District",
        "corridor": "NH-29 Kohima-Dimapur (Km 132 to 141)",
        "state": "nagaland",
        "slopeGradient": "37.5°",
        "soilPoreSaturation": "74.8%",
        "displacementRate": "4.9 mm/hr",
        "pwpPressure": "172 kPa",
        "riskStatus": "ADVISORY ORANGE",
        "rfConfidence": "84.6%",
        "lstmEvac": "10h 40m",
        "highwaySegment": "NH-29 Kohima Corridor",
        "bridgesExposed": "Sechü River Culvert",
        "populationRunout": "540 Residents",
        "coords": "25.6751° N, 94.1086° E",
        "elevation": "1,444 m",
        "top": "39%",
        "left": "82%",
        "isCritical": False,
        "hazardScore": 5.9,
    },
    {
        "id": "zone-mz-08",
        "name": "Aizawl Hill Cut",
        "subDivision": "Aizawl District",
        "corridor": "NH-6 Aizawl-Seling (Km 8 to 16)",
        "state": "mizoram",
        "slopeGradient": "46.2°",
        "soilPoreSaturation": "83.5%",
        "displacementRate": "8.1 mm/hr",
        "pwpPressure": "226 kPa",
        "riskStatus": "CRITICAL RED",
        "rfConfidence": "92.8%",
        "lstmEvac": "05h 15m",
        "highwaySegment": "NH-6 Aizawl Corridor",
        "bridgesExposed": "Tlawng Valley Span",
        "populationRunout": "1,080 Residents",
        "coords": "23.7271° N, 92.7176° E",
        "elevation": "1,132 m",
        "top": "73%",
        "left": "53%",
        "isCritical": True,
        "hazardScore": 8.1,
    },
    {
        "id": "zone-tr-09",
        "name": "Jampui Hills Ridge",
        "subDivision": "North Tripura District",
        "corridor": "Jampui Hills Access Road (Km 4 to 12)",
        "state": "tripura",
        "slopeGradient": "31.4°",
        "soilPoreSaturation": "68.9%",
        "displacementRate": "2.6 mm/hr",
        "pwpPressure": "128 kPa",
        "riskStatus": "NOMINAL GREEN",
        "rfConfidence": "78.5%",
        "lstmEvac": "24h+ Stable",
        "highwaySegment": "Jampui Hills Ridge Road",
        "bridgesExposed": "Kanchanpur Stream Bridge",
        "populationRunout": "260 Residents",
        "coords": "24.0560° N, 92.2500° E",
        "elevation": "760 m",
        "top": "78%",
        "left": "46%",
        "isCritical": False,
        "hazardScore": 2.1,
    },
    {
        "id": "zone-ar-01",
        "name": "Bhalukpong–Bomdila Ghat Corridor",
        "subDivision": "West Kameng District",
        "corridor": "Balipara–Charduar–Tawang Road (Km 42 to 58)",
        "state": "arunachal",
        "slopeGradient": "42.0°",
        "soilPoreSaturation": "76.4%",
        "displacementRate": "5.2 mm/hr",
        "pwpPressure": "185 kPa",
        "riskStatus": "ADVISORY ORANGE",
        "rfConfidence": "88.5%",
        "lstmEvac": "07h 40m",
        "highwaySegment": "NH-13 Trans-Arunachal Hwy",
        "bridgesExposed": "Kameng River Suspension Bridge",
        "populationRunout": "580 Residents",
        "coords": "27.0125° N, 92.6458° E",
        "elevation": "1,890 m",
        "top": "24%",
        "left": "52%",
        "isCritical": False,
        "hazardScore": 5.8,
    },
    {
        "id": "zone-ar-02",
        "name": "Tawang–Sela Pass Mountain Highway",
        "subDivision": "Tawang District",
        "corridor": "NH-13 Sela Pass Alpine Sector (Km 88 to 104)",
        "state": "arunachal",
        "slopeGradient": "47.8°",
        "soilPoreSaturation": "88.9%",
        "displacementRate": "12.4 mm/hr",
        "pwpPressure": "268 kPa",
        "riskStatus": "CRITICAL RED",
        "rfConfidence": "95.3%",
        "lstmEvac": "03h 15m",
        "highwaySegment": "NH-13 Sela Tunnel Approach",
        "bridgesExposed": "Baisakhi Bailey Span",
        "populationRunout": "420 Transit Passengers & Garrison",
        "coords": "27.5020° N, 92.1030° E",
        "elevation": "4,170 m",
        "top": "20%",
        "left": "48%",
        "isCritical": True,
        "hazardScore": 9.1,
    },
    {
        "id": "zone-ar-03",
        "name": "Pasighat–Pangin Siang Highway",
        "subDivision": "East Siang District",
        "corridor": "Siang River Gorge Highway (Km 18 to 32)",
        "state": "arunachal",
        "slopeGradient": "41.5°",
        "soilPoreSaturation": "84.2%",
        "displacementRate": "8.6 mm/hr",
        "pwpPressure": "215 kPa",
        "riskStatus": "ADVISORY ORANGE",
        "rfConfidence": "87.1%",
        "lstmEvac": "06h 45m",
        "highwaySegment": "NH-513 Siang Corridor",
        "bridgesExposed": "Ranaghat Siang Crossing",
        "populationRunout": "640 Residents",
        "coords": "28.1833° N, 95.0667° E",
        "elevation": "320 m",
        "top": "16%",
        "left": "68%",
        "isCritical": False,
        "hazardScore": 6.7,
    },
    {
        "id": "zone-sk-02",
        "name": "Gangtok–Nathula Border Highway",
        "subDivision": "East Sikkim",
        "corridor": "JN Road (Km 14 to 26)",
        "state": "sikkim",
        "slopeGradient": "49.1°",
        "soilPoreSaturation": "91.8%",
        "displacementRate": "13.5 mm/hr",
        "pwpPressure": "276 kPa",
        "riskStatus": "CRITICAL RED",
        "rfConfidence": "97.2%",
        "lstmEvac": "03h 30m",
        "highwaySegment": "NH-310 JN Road Corridor",
        "bridgesExposed": "Kyongnosla Alpine Bridge",
        "populationRunout": "860 Tourists & Border Personnel",
        "coords": "27.3516° N, 88.6667° E",
        "elevation": "2,950 m",
        "top": "38%",
        "left": "42%",
        "isCritical": True,
        "hazardScore": 9.4,
    },
    {
        "id": "zone-sk-03",
        "name": "Dikchu–Singtam Vulnerable Sinks",
        "subDivision": "North Sikkim",
        "corridor": "Dikchu–Mangan Arterial Road (SH-2)",
        "state": "sikkim",
        "slopeGradient": "43.4°",
        "soilPoreSaturation": "79.6%",
        "displacementRate": "6.8 mm/hr",
        "pwpPressure": "202 kPa",
        "riskStatus": "ADVISORY ORANGE",
        "rfConfidence": "89.0%",
        "lstmEvac": "08h 10m",
        "highwaySegment": "SH-2 Dikchu Valley Link",
        "bridgesExposed": "Dikchu River Barrage Bridge",
        "populationRunout": "720 Residents",
        "coords": "27.3917° N, 88.5283° E",
        "elevation": "920 m",
        "top": "35%",
        "left": "40%",
        "isCritical": False,
        "hazardScore": 6.5,
    },
    {
        "id": "zone-as-03",
        "name": "Jatinga–Harangajao NH-27 Corridor",
        "subDivision": "Dima Hasao District",
        "corridor": "East-West Corridor NH-27 (Km 120 to 135)",
        "state": "assam",
        "slopeGradient": "45.0°",
        "soilPoreSaturation": "89.4%",
        "displacementRate": "11.8 mm/hr",
        "pwpPressure": "254 kPa",
        "riskStatus": "CRITICAL RED",
        "rfConfidence": "94.8%",
        "lstmEvac": "04h 05m",
        "highwaySegment": "NH-27 East-West Expressway",
        "bridgesExposed": "Jatinga River Bridge #3",
        "populationRunout": "1,150 Residents",
        "coords": "25.0833° N, 92.9333° E",
        "elevation": "620 m",
        "top": "54%",
        "left": "60%",
        "isCritical": True,
        "hazardScore": 8.9,
    },
    {
        "id": "zone-as-04",
        "name": "Guwahati–Kamakhya Nilachal Hillslope",
        "subDivision": "Kamrup Metropolitan",
        "corridor": "Nilachal Hill Access & Foothills Artery",
        "state": "assam",
        "slopeGradient": "36.5°",
        "soilPoreSaturation": "72.3%",
        "displacementRate": "3.8 mm/hr",
        "pwpPressure": "158 kPa",
        "riskStatus": "NOMINAL GREEN",
        "rfConfidence": "81.4%",
        "lstmEvac": "18h+ Stable",
        "highwaySegment": "Kamakhya Temple Hill Road",
        "bridgesExposed": "Brahmaputra Bank Overpass",
        "populationRunout": "2,400 Pilgrims & Residents",
        "coords": "26.1667° N, 91.7050° E",
        "elevation": "240 m",
        "top": "46%",
        "left": "52%",
        "isCritical": False,
        "hazardScore": 2.5,
    },
    {
        "id": "zone-ml-02",
        "name": "Shillong–Dawki NH-206 Escarpment",
        "subDivision": "East Khasi Hills",
        "corridor": "Pynursla Gorge Corridor (Km 45 to 56)",
        "state": "meghalaya",
        "slopeGradient": "46.8°",
        "soilPoreSaturation": "87.5%",
        "displacementRate": "9.4 mm/hr",
        "pwpPressure": "238 kPa",
        "riskStatus": "CRITICAL RED",
        "rfConfidence": "93.5%",
        "lstmEvac": "05h 10m",
        "highwaySegment": "NH-206 Shillong–Dawki Road",
        "bridgesExposed": "Wah Umngot Suspension Span",
        "populationRunout": "820 Residents",
        "coords": "25.3167° N, 91.9000° E",
        "elevation": "1,420 m",
        "top": "56%",
        "left": "52%",
        "isCritical": True,
        "hazardScore": 8.6,
    },
    {
        "id": "zone-ml-04",
        "name": "Umiam Lake–Nongpoh NH-6 Artery",
        "subDivision": "Ri-Bhoi District",
        "corridor": "Guwahati–Shillong Highway (Km 62 to 78)",
        "state": "meghalaya",
        "slopeGradient": "38.2°",
        "soilPoreSaturation": "75.4%",
        "displacementRate": "5.1 mm/hr",
        "pwpPressure": "178 kPa",
        "riskStatus": "ADVISORY ORANGE",
        "rfConfidence": "85.9%",
        "lstmEvac": "09h 30m",
        "highwaySegment": "NH-6 GS Road Corridor",
        "bridgesExposed": "Umiam Spillway Bridge",
        "populationRunout": "1,320 Transit Commuters",
        "coords": "25.7167° N, 91.8833° E",
        "elevation": "980 m",
        "top": "52%",
        "left": "50%",
        "isCritical": False,
        "hazardScore": 5.7,
    },
    {
        "id": "zone-mn-02",
        "name": "Imphal–Dimapur NH-2 Senapati Corridor",
        "subDivision": "Senapati District",
        "corridor": "Maram–Tadubi Mountain Artery (Km 210 to 226)",
        "state": "manipur",
        "slopeGradient": "42.7°",
        "soilPoreSaturation": "82.1%",
        "displacementRate": "7.9 mm/hr",
        "pwpPressure": "212 kPa",
        "riskStatus": "ADVISORY ORANGE",
        "rfConfidence": "89.2%",
        "lstmEvac": "06h 50m",
        "highwaySegment": "NH-2 Asian Highway 1",
        "bridgesExposed": "Barak River Upper Bridge",
        "populationRunout": "890 Residents",
        "coords": "25.2667° N, 94.0167° E",
        "elevation": "1,450 m",
        "top": "64%",
        "left": "78%",
        "isCritical": False,
        "hazardScore": 6.8,
    },
    {
        "id": "zone-mn-03",
        "name": "Lokchao–Moreh Border Highway Cut",
        "subDivision": "Tengnoupal District",
        "corridor": "NH-102 Trans-Asian Highway (Km 72 to 85)",
        "state": "manipur",
        "slopeGradient": "40.6°",
        "soilPoreSaturation": "79.3%",
        "displacementRate": "6.2 mm/hr",
        "pwpPressure": "188 kPa",
        "riskStatus": "ADVISORY ORANGE",
        "rfConfidence": "84.8%",
        "lstmEvac": "08h 40m",
        "highwaySegment": "NH-102 Imphal–Moreh Link",
        "bridgesExposed": "Lokchao River Culvert",
        "populationRunout": "490 Residents & Trade Hub",
        "coords": "24.3167° N, 94.2833° E",
        "elevation": "510 m",
        "top": "72%",
        "left": "80%",
        "isCritical": False,
        "hazardScore": 5.6,
    },
    {
        "id": "zone-na-02",
        "name": "Chumoukedima–Piphima NH-29 Pagla Pahar",
        "subDivision": "Chumoukedima District",
        "corridor": "Old NH-39 Gorge Corridor (Km 122 to 134)",
        "state": "nagaland",
        "slopeGradient": "48.2°",
        "soilPoreSaturation": "90.5%",
        "displacementRate": "12.8 mm/hr",
        "pwpPressure": "272 kPa",
        "riskStatus": "CRITICAL RED",
        "rfConfidence": "96.5%",
        "lstmEvac": "03h 40m",
        "highwaySegment": "NH-29 Dimapur–Kohima Bypass",
        "bridgesExposed": "Chathe River Viaduct",
        "populationRunout": "1,280 Residents",
        "coords": "25.7833° N, 93.8167° E",
        "elevation": "620 m",
        "top": "42%",
        "left": "80%",
        "isCritical": True,
        "hazardScore": 9.2,
    },
    {
        "id": "zone-na-03",
        "name": "Mokokchung–Tuensang Mountain Road",
        "subDivision": "Mokokchung District",
        "corridor": "NH-702D Ridge Highway (Km 35 to 48)",
        "state": "nagaland",
        "slopeGradient": "39.8°",
        "soilPoreSaturation": "76.2%",
        "displacementRate": "5.5 mm/hr",
        "pwpPressure": "182 kPa",
        "riskStatus": "ADVISORY ORANGE",
        "rfConfidence": "86.4%",
        "lstmEvac": "08h 50m",
        "highwaySegment": "NH-702D Mokokchung Artery",
        "bridgesExposed": "Milak River Crossing",
        "populationRunout": "510 Residents",
        "coords": "26.3244° N, 94.5208° E",
        "elevation": "1,325 m",
        "top": "36%",
        "left": "85%",
        "isCritical": False,
        "hazardScore": 6.1,
    },
    {
        "id": "zone-mz-02",
        "name": "Lunglei–Thenzawl State Highway Pass",
        "subDivision": "Lunglei District",
        "corridor": "SH-1 South Artery (Km 28 to 42)",
        "state": "mizoram",
        "slopeGradient": "44.8°",
        "soilPoreSaturation": "85.4%",
        "displacementRate": "8.7 mm/hr",
        "pwpPressure": "232 kPa",
        "riskStatus": "CRITICAL RED",
        "rfConfidence": "93.1%",
        "lstmEvac": "05h 00m",
        "highwaySegment": "SH-1 Thenzawl Ghat Road",
        "bridgesExposed": "Lau River Span",
        "populationRunout": "670 Residents",
        "coords": "22.8833° N, 92.7333° E",
        "elevation": "1,220 m",
        "top": "80%",
        "left": "54%",
        "isCritical": True,
        "hazardScore": 8.7,
    },
    {
        "id": "zone-mz-03",
        "name": "Sairang–Lengpui Airport Ghat Road",
        "subDivision": "Aizawl District",
        "corridor": "NH-108 Airport Corridor (Km 12 to 24)",
        "state": "mizoram",
        "slopeGradient": "41.2°",
        "soilPoreSaturation": "78.8%",
        "displacementRate": "5.9 mm/hr",
        "pwpPressure": "190 kPa",
        "riskStatus": "ADVISORY ORANGE",
        "rfConfidence": "87.8%",
        "lstmEvac": "07h 30m",
        "highwaySegment": "NH-108 Lengpui Airport Link",
        "bridgesExposed": "Tlawng River Suspension",
        "populationRunout": "840 Passengers & Personnel",
        "coords": "23.8167° N, 92.6333° E",
        "elevation": "420 m",
        "top": "71%",
        "left": "51%",
        "isCritical": False,
        "hazardScore": 6.3,
    },
    {
        "id": "zone-tr-02",
        "name": "Ambassa–Atharamura Hill Range Corridor",
        "subDivision": "Dhalai District",
        "corridor": "NH-8 National Highway Cut (Km 68 to 82)",
        "state": "tripura",
        "slopeGradient": "35.6°",
        "soilPoreSaturation": "71.5%",
        "displacementRate": "3.4 mm/hr",
        "pwpPressure": "142 kPa",
        "riskStatus": "NOMINAL GREEN",
        "rfConfidence": "80.2%",
        "lstmEvac": "20h+ Stable",
        "highwaySegment": "NH-8 Agartala–Silchar Highway",
        "bridgesExposed": "Dhalai River Span",
        "populationRunout": "480 Residents",
        "coords": "23.9167° N, 91.8500° E",
        "elevation": "310 m",
        "top": "76%",
        "left": "44%",
        "isCritical": False,
        "hazardScore": 2.4,
    },
]

INITIAL_SENSOR_NODES = [
    {
        "id": "SN-SK-01",
        "name": "Borehole Piezometer Array #1",
        "type": "piezometer",
        "typeLabel": "Vibrating Wire Piezometer",
        "location": "Mangan-Dikchu Ridge (Ch 36.4)",
        "state": "sikkim",
        "coordinates": "27.5312° N, 88.5134° E",
        "battery": "94%",
        "uplink": "GSAT-7A Mesh",
        "lastSync": "4 sec ago",
        "currentValue": "284 kPa",
        "currentValueSub": "+18 kPa/hr surge",
        "warningThreshold": "260 kPa",
        "thresholdPercentage": 109,
        "status": "critical",
        "statusLabel": "RUPTURE PRESSURE CRITICAL",
        "sparkline": [180, 195, 215, 230, 252, 268, 284],
        "depth": "14.2m Sub-surface",
    },
    {
        "id": "SN-SK-02",
        "name": "In-Place Inclinometer String #4",
        "type": "inclinometer",
        "typeLabel": "MEMS Inclinometer (Bi-Axial)",
        "location": "Singtam Cut-Slope Benchmark",
        "state": "sikkim",
        "coordinates": "27.2341° N, 88.4988° E",
        "battery": "88%",
        "uplink": "Optical Fibre SDMA",
        "lastSync": "12 sec ago",
        "currentValue": "14.2 mm/hr",
        "currentValueSub": "Shear Strain Rate",
        "warningThreshold": "8.0 mm/hr",
        "thresholdPercentage": 177,
        "status": "critical",
        "statusLabel": "ACCELERATING CREEP DETECTED",
        "sparkline": [2.1, 3.4, 4.8, 6.2, 8.9, 11.5, 14.2],
        "depth": "8.5m Slip Interface",
    },
    {
        "id": "SN-MZ-03",
        "name": "Acoustic Emission Waveguide #2",
        "type": "acoustic",
        "typeLabel": "Sub-surface Micro-seismic AE",
        "location": "Champhai Fault Shear Plane",
        "state": "mizoram",
        "coordinates": "23.4756° N, 93.3281° E",
        "battery": "76%",
        "uplink": "LoRaWAN Gateway MZ-04",
        "lastSync": "30 sec ago",
        "currentValue": "4,120 hits/min",
        "currentValueSub": "Ringdown Count",
        "warningThreshold": "2,500 hits/min",
        "thresholdPercentage": 164,
        "status": "critical",
        "statusLabel": "INTERNAL MICRO-FRACTURING SPIKE",
        "sparkline": [600, 850, 1200, 1800, 2400, 3200, 4120],
        "depth": "18.0m Bedrock Joint",
    },
    {
        "id": "SN-ML-04",
        "name": "Optical Tipping Bucket + AWS",
        "type": "aws",
        "typeLabel": "Automated Weather Station (IMD)",
        "location": "Cherrapunji Plateau Ridge AWS-1",
        "state": "meghalaya",
        "coordinates": "25.2986° N, 91.7322° E",
        "battery": "99%",
        "uplink": "IMD Doppler Sync",
        "lastSync": "1 min ago",
        "currentValue": "84 mm/hr",
        "currentValueSub": "Antecedent 72h: 312 mm",
        "warningThreshold": "50 mm/hr",
        "thresholdPercentage": 168,
        "status": "torrential",
        "statusLabel": "TORRENTIAL MONSOON BURST",
        "sparkline": [12, 24, 38, 55, 68, 76, 84],
        "depth": "Surface Met Mast (10m)",
    },
    {
        "id": "SN-UK-05",
        "name": "Ridge Bypass Inclinometer",
        "type": "inclinometer",
        "typeLabel": "MEMS Inclinometer",
        "location": "Uttarkashi Ridge Bypass Cut",
        "state": "uttarakhand",
        "coordinates": "30.7268° N, 78.4354° E",
        "battery": "91%",
        "uplink": "GSAT-7A Mesh",
        "lastSync": "18 sec ago",
        "currentValue": "7.6 mm/hr",
        "currentValueSub": "Slope displacement rate",
        "warningThreshold": "8.0 mm/hr",
        "thresholdPercentage": 95,
        "status": "advisory",
        "statusLabel": "CREEP ABOVE BASELINE",
        "sparkline": [2.1, 2.8, 3.7, 4.5, 5.9, 6.8, 7.6],
        "depth": "9.0m Slip Interface",
    },
    {
        "id": "SN-NA-06",
        "name": "Kohima AWS Ridge Node",
        "type": "aws",
        "typeLabel": "Automated Weather Station",
        "location": "Kohima Escarpment NH-29",
        "state": "nagaland",
        "coordinates": "25.6751° N, 94.1086° E",
        "battery": "96%",
        "uplink": "LoRaWAN Gateway NA-02",
        "lastSync": "24 sec ago",
        "currentValue": "22 mm/hr",
        "currentValueSub": "Antecedent 72h: 164 mm",
        "warningThreshold": "50 mm/hr",
        "thresholdPercentage": 44,
        "status": "advisory",
        "statusLabel": "RAIN BAND MONITORING",
        "sparkline": [8, 12, 10, 15, 18, 20, 22],
        "depth": "Surface Met Mast (10m)",
    },
    {
        "id": "SN-TR-07",
        "name": "Jampui Hills Rain Gauge",
        "type": "aws",
        "typeLabel": "Automated Weather Station",
        "location": "Jampui Hills Ridge Road",
        "state": "tripura",
        "coordinates": "24.0560° N, 92.2500° E",
        "battery": "98%",
        "uplink": "LoRaWAN Gateway TR-01",
        "lastSync": "42 sec ago",
        "currentValue": "8 mm/hr",
        "currentValueSub": "Antecedent 72h: 86 mm",
        "warningThreshold": "50 mm/hr",
        "thresholdPercentage": 16,
        "status": "nominal",
        "statusLabel": "NOMINAL PRECIPITATION",
        "sparkline": [4, 6, 5, 7, 8, 7, 8],
        "depth": "Surface Met Mast (10m)",
    },
]

INITIAL_REPORTS = [
    {
        "id": "rep-sk-101",
        "code": "SK-FLD-2024-098",
        "location": "NH-10 Km 38.4 (Lower Singtam Slide)",
        "subDivision": "Mangan Sub-Division",
        "state": "sikkim",
        "timeAgo": "14 min ago",
        "reportedTime": "14:28 IST",
        "urgency": "CRITICAL",
        "verifiedBy": "AI-YOLOv8 Geotech Vision (Edge Verified)",
        "imageUrl": "https://lh3.googleusercontent.com/aida-public/AB6AXuCfgmZOUw0RJNRDeRn_ey0LAUAFSBdB0JYQGzipb_eWiyc-h1uSGualH0defPe8gbGXbegaDiukL0iel6AWkyGhqwL0BSjmQdsUol2ad9E0y8npvwgJykhtYJwOmGbJ3NOgIsm8kZitQiHwkRuDW1Dkq9c_HVHDUmAq9_UahiuhMl-e4ReMnP62Yc1QcBB0l7Jl10W0VogIPMNZAoUuMA4O38M_RyvqjrRcTeCXK5vXVdvEyXLEy06Xfg",
        "imageAlt": "Active rotational slope failure breaching NH-10 road surface with mud slurry runout",
        "cvRisk": "98.4%",
        "cvLabel": "Active Rotational Shear Scarp with Tension Fissure",
        "cvModel": "YOLOv8-Geotech-NER v4.2",
        "summary": "Crown shear scarp ~45m width detected. Tension fissures propagating across NH-10 carriageway. Active mud runout.",
        "description": "Massive toe blowout observed at retaining crib wall below NH-10 Km 38.4. Boulder fall actively blocking single carriageway lane. Road surface has subsided approximately 400mm.",
        "coordinates": "27.2388° N, 88.5012° E",
        "elevation": "1,420 m",
        "slope": "48.5°",
        "precipitation": "84 mm/h (IMD Extreme Influx)",
        "exifStatus": "GPS & Cryptographic Hash Verified (GSAT Uplink)",
        "audioLanguage": "Nepali (Eastern Sub-dialect)",
        "audioDuration": "0:24",
        "vernacularText": "बाटो मुनिबाट माटो बग्न थालेको छ। ठूला ढुङ्गाहरू तल खसिरहेका छन् र बाटो भाँसिएको छ। तुरून्तै मद्दत पठाउनुहोस्!",
        "englishTranslation": "Soil has started giving way from below the road. Huge boulders are actively tumbling down and the pavement has sunken. Send immediate assistance!",
        "sensorCorroboration": {
            "sensorId": "SN-SK-01",
            "rate": "+18 kPa/hr PWP Spike",
            "thresholdMessage": "Breached 280 kPa critical shear failure threshold",
        },
        "boundingBoxes": [
            {
                "label": "Crown Shear Scarp (45m)",
                "confidence": "98.4%",
                "top": "12%",
                "left": "18%",
                "width": "64%",
                "height": "32%",
                "color": "error",
            },
            {
                "label": "Roadway Carriageway Tension Crack",
                "confidence": "94.2%",
                "top": "54%",
                "left": "28%",
                "width": "50%",
                "height": "22%",
                "color": "tertiary",
            },
            {
                "label": "Toe Slurry Runout Toe Breach",
                "confidence": "91.0%",
                "top": "68%",
                "left": "45%",
                "width": "35%",
                "height": "24%",
                "color": "secondary",
            },
        ],
        "status": "active",
    },
]

INITIAL_TACTICAL_UNITS = [
    {
        "id": "tu-ndrf-01",
        "name": "12th Bn NDRF Task Force (Bravo Co.)",
        "status": "EN ROUTE",
        "statusLabel": "Transit on NH-10 (Km 28.2)",
        "eta": "24 min",
        "personnel": 45,
        "description": "Heavy urban search & rescue, hydraulic cutters, in-situ life detector radar, and drone reconnaissance squadron.",
        "destination": "Teesta Basin Lower Singtam Slide (Km 38.4)",
        "satcomStatus": "GSAT-7A BGAN Online",
        "equipment": ["Life Detectors x4", "Hydraulic Cutters x6", "Inflatable Rafts x2", "UAV Fleet x3"],
        "progressPercent": 65,
        "type": "ndrf",
    },
    {
        "id": "tu-bro-02",
        "name": "BRO Project Swastik Task Force",
        "status": "ACTIVE",
        "statusLabel": "Site Staging at Mile-32 Depot",
        "eta": "12 min",
        "personnel": 32,
        "description": "Border Roads Organisation earthmoving division deploying heavy excavators, rock breakers, and pre-fab Bailey bridging gear.",
        "destination": "NH-10 Km 38.4 Breach Site",
        "satcomStatus": "VHF High-Band Active",
        "equipment": ["Komatsu Excavators x2", "JCB Heavy Loader x3", "Bailey Span Parts 30m"],
        "progressPercent": 85,
        "type": "bro",
    },
]

INITIAL_RELIEF_SHELTERS = [
    {
        "id": "sh-01",
        "name": "Singtam Govt Senior Secondary School Camp",
        "location": "Singtam Upper Ridge Ground",
        "state": "sikkim",
        "capacityCurrent": 340,
        "capacityMax": 600,
        "occupancyPercent": 56,
        "status": "AVAILABLE",
        "rationsDays": "14 Days Dry Stock",
        "gensetStatus": "45 kVA Online",
        "waterSupply": "Potable Gravity Feed Active",
        "medicalActive": True,
    },
    {
        "id": "sh-02",
        "name": "Rangpo Community Disaster Relief Pavilion",
        "location": "Rangpo Stadium Complex",
        "state": "sikkim",
        "capacityCurrent": 720,
        "capacityMax": 800,
        "occupancyPercent": 90,
        "status": "CRITICAL",
        "rationsDays": "6 Days Stock",
        "gensetStatus": "Diesel Low (4 hrs)",
        "waterSupply": "Boil Water Advisory",
        "medicalActive": True,
    },
]

def seed_database():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        # Seed Hazard Zones
        for item in INITIAL_HAZARD_ZONES:
            if not db.query(HazardZoneModel).filter(HazardZoneModel.id == item["id"]).first():
                db.add(HazardZoneModel(**item))

        # Seed Sensors
        for item in INITIAL_SENSOR_NODES:
            if not db.query(SensorNodeModel).filter(SensorNodeModel.id == item["id"]).first():
                db.add(SensorNodeModel(**item))

        # Seed Reports
        if db.query(CrowdsourceReportModel).count() == 0:
            for item in INITIAL_REPORTS:
                db.add(CrowdsourceReportModel(**item))

        # Seed Units
        if db.query(TacticalUnitModel).count() == 0:
            for item in INITIAL_TACTICAL_UNITS:
                db.add(TacticalUnitModel(**item))

        # Seed Shelters
        if db.query(ReliefShelterModel).count() == 0:
            for item in INITIAL_RELIEF_SHELTERS:
                db.add(ReliefShelterModel(**item))

        db.commit()
        print("Database seeded successfully.")
    except Exception as e:
        db.rollback()
        print(f"Error seeding database: {e}")
    finally:
        db.close()

if __name__ == "__main__":
    seed_database()
